name: Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # OpenJDK
          java-version: '11'
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
        run: pip install --force-reinstall "cryptography==38.0.4"         
      - name: Install dependencies
        run: cd core && yarn install --check-files --frozen-lockfile
      - name: Set git identity
        run: |-
          git config user.name "Automation"
          git config user.email "github-actions@github.com"
      - name: Build
        run: cd core && npx projen build
      - name: Check for changes
        id: git_diff
        run: git diff --exit-code || echo "::set-output name=has_changes::true"
      - if: steps.git_diff.outputs.has_changes
        name: Commit and push changes (if changed)
        run: 'git add . && git commit -m "chore: self mutation" && git push origin
          HEAD:${{ github.event.pull_request.head.ref }}'
      - if: steps.git_diff.outputs.has_changes
        name: Update status check (if changed)
        run: gh api -X POST /repos/${{ github.event.pull_request.head.repo.full_name
          }}/check-runs -F name="build" -F head_sha="$(git rev-parse HEAD)" -F
          status="completed" -F conclusion="success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: jsii/superchain:1-buster-slim-node14
